#!/bin/bash

rules="CONTENT=$(cat $1)"
rules=`echo "$rules" | tr '\n' ' '`
CONTENT=$(cat $1 | tr '\n' ' ')

mapfile -t keywords < <(< <(echo "$rules") sed -n 's/^\([A-Za-z0-9_]\+\)=.*$/\1/p')

while read line
do
  for keyword in "${keywords[@]}"
  do
    line=`sed "s@\@${keyword}\@@${!keyword}@g" <<<"$line"`
  done 
  echo "$line"
done < /dev/stdin 
